/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Female/FemalD.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";
import { useCustomization } from '../src/context/Customization';

const FemalD = (props) => {
  const {skinColor,material,legs} = useCustomization();

  const { nodes, materials } = useGLTF('./models/Female/FemalD.gltf')
  
  const skinTextureProps = useTexture({
    //map: './public/textures/skin/Skin_Human_002_COLOR.png',
    normalMap: './public/textures/skin/Skin_Human_002_NRM.png',
    //roughnessMap: './public/textures/skin/Skin_Human_002_SPEC.png',
    aoMap: './public/textures/skin/Skin_Human_002_OCC.png',
  })

  const clothBTextureProps = useTexture({
    map: './public/textures/cloth/01/Fabric_Knitted_006_basecolor.jpg',
    normalMap: './public/textures/cloth/01/Fabric_Knitted_006_Normal.jpg',
    roughnessMap: './public/textures/cloth/01/Fabric_Knitted_006_Roughness.jpg',
    aoMap: './public/textures/cloth/01/Fabric_Knitted_006_AmbientOcclusion.jpg',
  })

  const clothRTextureProps = useTexture({
    map: './public/textures/cloth/02/Fabric_Lace_019_basecolor.jpg',
    normalMap: './public/textures/cloth/02/Fabric_Lace_019_normal.jpg',
    roughnessMap: './public/textures/cloth/02/Fabric_Lace_019_roughness.jpg',
    aoMap: './public/textures/cloth/02/Fabric_Lace_019_ambientOcclusion.jpg',
  })

  //skinTextureProps.map.repeat.set(3,3);
  skinTextureProps.normalMap.repeat.set(3,3);
  skinTextureProps.aoMap.repeat.set(3,3);

  //skinTextureProps.map.wrapS = skinTextureProps.map.wrapT = THREE.RepeatWrapping; 
  skinTextureProps.normalMap.wrapS = skinTextureProps.normalMap.wrapT = THREE.RepeatWrapping; 
  skinTextureProps.aoMap.wrapS = skinTextureProps.aoMap.wrapT = THREE.RepeatWrapping; 

  clothRTextureProps.map.wrapS=clothRTextureProps.map.wrapT = THREE.RepeatWrapping;
  clothRTextureProps.normalMap.wrapS=clothRTextureProps.normalMap.wrapT = THREE.RepeatWrapping;
  clothRTextureProps.roughnessMap.wrapS=clothRTextureProps.roughnessMap.wrapT = THREE.RepeatWrapping;
  clothRTextureProps.aoMap.wrapS=clothRTextureProps.aoMap.wrapT = THREE.RepeatWrapping;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} rotation={[Math.PI / 2, 0, 0]}>
         <meshStandardMaterial{...skinTextureProps} color={skinColor} roughness={1} />
      </mesh>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.eyebrow_1.geometry} material={materials._defaultMat1} />
        <mesh geometry={nodes.eyebrow_2.geometry} material={materials.lambert2} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.eyelash_1.geometry} >
          <meshBasicMaterial color="#000000"/>
        </mesh>
        <mesh geometry={nodes.eyelash_2.geometry} >
        <meshBasicMaterial color="#000000"/>
        </mesh>
      </group>
      <mesh geometry={nodes.eyes.geometry}  rotation={[Math.PI / 2, 0, 0]} >
      <meshBasicMaterial color="#000000"/>
      </mesh>
      <mesh geometry={nodes.shoes.geometry} material={materials.lambert2} rotation={[Math.PI / 2, 0, 0]} >
        <meshBasicMaterial color="#000000"/>
      </mesh>
      <mesh geometry={nodes.d026_lowMesh.geometry} position={[2.132, -22.803, 0.57]} rotation={[Math.PI / 2, 0, 0]} scale={0.11} visible = {legs ===1 } >
      <meshStandardMaterial {...material === "Frabric 01" ?clothBTextureProps : clothRTextureProps}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Female/FemalD.gltf')

export default FemalD;