/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Female/ManikanF.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";
import { useCustomization } from '../src/context/Customization';

const ManikanF =(props) => {

  const {skinColor} = useCustomization();

  const { nodes, materials } = useGLTF('./models/Female/ManikanF.gltf')

  const skinTextureProps = useTexture({
    //map: './public/textures/skin/Skin_Human_002_COLOR.png',
    normalMap: './public/textures/skin/Skin_Human_002_NRM.png',
    //roughnessMap: './public/textures/skin/Skin_Human_002_SPEC.png',
    aoMap: './public/textures/skin/Skin_Human_002_OCC.png',
  })

  //skinTextureProps.map.repeat.set(3,3);
  skinTextureProps.normalMap.repeat.set(3,3);
  skinTextureProps.aoMap.repeat.set(3,3);

  //skinTextureProps.map.wrapS = skinTextureProps.map.wrapT = THREE.RepeatWrapping; 
  skinTextureProps.normalMap.wrapS = skinTextureProps.normalMap.wrapT = THREE.RepeatWrapping; 
  skinTextureProps.aoMap.wrapS = skinTextureProps.aoMap.wrapT = THREE.RepeatWrapping; 

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} rotation={[Math.PI / 2, 0, 0]}>
        <meshStandardMaterial{...skinTextureProps} color={skinColor} />
      </mesh>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.eyebrow_1.geometry} material={materials._defaultMat1} />
        <mesh geometry={nodes.eyebrow_2.geometry} material={materials.lambert2} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.eyelash_1.geometry} material={materials._defaultMat1} />
        <mesh geometry={nodes.eyelash_2.geometry} material={materials.lambert2} />
      </group>
      <mesh geometry={nodes.eyes.geometry} material={materials._defaultMat1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.shoes.geometry} material={materials.lambert2} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/Female/ManikanF.gltf')

export default ManikanF;
